(()=>{'use strict';
const help=document.querySelector('a[href="/segedlet"]');if(!help)return;
const guide=document.createElement('main');guide.className='local-guide';guide.hidden=true;guide.innerHTML=`
<article class="local-guide-card">
 <img class="local-guide-seal" src="assets/btk.seepd.hu/los_santos_91aa4398.webp" alt="Los Santos címere">
 <h1>BÜNTETŐ TÖRVÉNYKÖNYV - LOS SANTOS</h1>
 <h2>Maximum büntetésre vonatkozó szabályok</h2><p><b>Max börtönidő:</b> <em>120 Perc</em><br><b>Max bírság:</b> <em>5.000.000 $</em></p>
 <h2>Enyhítő körülmények</h2><p><b>[20-40% ajánlott]</b> Büntetlen előélet (MDC ellenőrzése minden esetben szükséges)<br><b>[10-20% ajánlott]</b> Hatóságokkal történő együttműködés<br><b>[50% ajánlott]</b> Kényszer hatására követte el a bűncselekményt<br><b>[20-30% ajánlott]</b> Elkövető önfeljelentése (Különösen, ha ennek folytán vált lehetővé a bűncselekmény felderítése, vagy azt jelentős mértékben elősegítette)<br><b>[20-30% ajánlott]</b> A bűnösségre is kiterjedő beismerő vallomás, illetve a részbeni beismerés. Nagyobb a nyomatéka, ha a beismerés segíti a felderítést. Tettenérés esetén csak a bűnösség elismerésének és a megbánás lehet enyhítő körülmény.</p>
 <h2>Óvadékkal kapcsolatos információk</h2><p>Óvadékra akkor van lehetőség ha azt egyik vád sem zárja ki ennek lehetőségét.<br>Óvadék megtagadására Rendőrség állományából Tisztnek, Sheriff's Office állományából Supervisornak vagy ennél magasabb beosztású személyeknek van lehetősége.<br><i>((LVL 10 alatti játékos nem kaphat óvadékot, büntetés mindig 1$ kell legyen.))</i></p>
 <h2>Enyhítésre vonatkozó szabályok</h2><p><i><b>Enyhítésnél a pénzbírságot és az időt külön-külön is lehet módosítani.</b></i></p><div class="guide-cols guide-cols-single"><p>Rendőrség enyhítési korlátok<br><b>Tiszthelyettesek:</b> <mark>10 %</mark><br><b>Zászlósok:</b> <mark>30 %</mark><br><b>Tisztek:</b> <mark>60 %</mark><br><b>Vezérkari tagok:</b> <mark>100 %</mark></p></div>
 <h2>Súlyosbításra vonatkozó szabályok</h2><p>Amennyiben egy előállítás során az előállított személy kimondottan rossz magaviseletet tanúsít, hátráltatja a folyamatot lehetőség van a büntetés súlyosbítására.<br>Tiszt / Supervisor maximum <em>60 nappal</em> hosszabbíthatja meg a büntetést.<br>Vezérkari tag / High Command maximum <em>100 nappal</em> hosszabbíthatja meg a büntetést.<br><em><b>Pénzbírság nem súlyosbítható.</b></em></p>
 <h2>Jármű lefoglalással kapcsolatos információk</h2><h3>See City Közút</h3><p>-</p><h3>Rendőrség</h3><p>-</p>
 <h2>Fegyverviseléssel kapcsolatos információk</h2><p>Az engedéllyel tartott fegyverek közül 1 típusból (lőfegyver / kés) csak egy-egy darab lehet egy időben valakinél. Az adott fegyvereket a tulajdonosa köteles rejtve hordani (Kiv. Rendvédelmi engedély).<br>Civil fegyverengedéllyel <span>60</span>, Rendvédelmi engedéllyel <span>100</span> lőszer tartható egyszerre.</p><h3>Engedéllyel tartható fegyverek listája</h3><p><i><b>Fegyverek csak rejtve viselhetőek!</b></i><br>Pistol [Csak magánterületen, nem rejtve is használható!]<br>Rugós kés<br>SNS Pistol<br>SNS Pistol MK2<br>Ceramic Pistol</p><p><b>Rendvédelmi engedéllyel a civil engedélyen felül továbbá viselhető akár láthatóan is:</b><br>Pistol<br>Heavy Pistol<br>Vintage Pistol<br>Pistol .50<br>Pistol MK2<br>Egyéb lőfegyver - Főkapitány egyéni esetben hozott döntése alapján</p>
 <h2>Ügyvédi kamara</h2><p>Hamarosan..</p>
 <h2>Vádalkura / Egyezségre vonatkozó szabályok</h2><p>Lehetőség van a rendvédelemmel vádalkut, egyezséget kötni amennyiben ezt mindkét fél elfogadja.<br>Ebben az esetben a rendvédelem köteles tiszteletben tartani az egyezséget mindaddig míg a másik fél is a megállapodás alapján cselekszik.<br><em><b>Gyilkossággal, Terrorcselekménnyel vádolt személyek nem köthetnek vádalkut sem egyezséget.</b></em></p>
 <h2>Körözések kiadása</h2><p>Szabálysértésre körözés nem adható ki.<br>Cserbenhagyás körözés csak akkor adható ki ha az ügyben eljáró személy részére rendelkezésre áll bizonyíték. Bizonyíték hiányában a körözést érvénytelennek kell tekinteni.<br>Megfigyelés körözés legfeljebb <em>30 napig</em> tartható kint, ezt követően az illetékes szervezet köteles visszavonni.<br>Lakossági bejelentés vagy feltételes alapon kiadott körözéseknél ezt a körülményt fel kell tüntetni.</p>
 <h2>Felülvizsgálati kérelmek</h2><p>Felülvizsgálati kérelem nyújtható be minden rendvédelmi eljárással kapcsolatban az illetékes szervezet weboldalán.<br>Bírálás megkezdésére a szervezeteknek 48 óra áll rendelkezésre, bírálást megkezdését követően 1 hét áll rendelkezésre az ügy kivizsgálására és lezárására.<br>A szervezetek vezetősége szabadon dönthet arról, hogy mely alosztályt vagy rendvédelmi állomány tagját jelöli ki a vizsgálat lefolytatására.<br>Felülvizsgálati kérelemben hozott döntés ellen további jogorvoslat nincs.</p><p>Amennyiben a felülvizsgálat az eljáró hatóság részéről eljárási hibát vél felfedezni, úgy kártérítésnek van helye.<br>Kártérítés összege legalább 150%-a, maximum 300%-a lehet a keletkezett kárnak.<br>A kárt a szervezet köteles megfizetni, azt nem háríthatja át az állomány tagjára.</p>
 <h2>Műszaki szabályozás</h2><h3>ENGEDÉLYEZETT LÁMPÁK:</h3><p>Gyári, Xenon, Kadmiumsárga xenon</p><p><b>A következő szervezetek jogosultak prefix használatra</b><br><b>Rendőrség:</b> <span>RA- ; RB- ; KR- ; NNI- ; TEK-</span><br><b>Blaine County Sheriff's Office:</b> <span>SD- ; SW- ; BC-SO- ; SHERIFF</span><br><b>Büntetés Végrehajtás:</b> <span>RR- ; BVI-</span><br><b>Országos Mentőszolgálat:</b> <span>MA- ; MB- ; OMSZ-</span><br><b>See City Közút:</b> <span>SCK-</span><br><b>See City Kormánya:</b> <span>GOV- ; A- ; E- ; Z-</span><br><b>Blaine County Kormánya:</b> <span>BGOV- ; A- ; E- ; Z-</span><br><b>Országos Polgárőr Szövetség:</b> <span>OPSZ-</span></p><p><b>See City Kormánya / Blaine County Kormánya engedélyével:</b><br><b>Diplomata Testületi</b> <span>DT- ; CC- ; CD- ; CK-</span></p>
</article>`;
guide.innerHTML='<article class="local-guide-card local-guide-coming"><h1>Cooming soon...</h1><p>Created by: Hexo</p></article>';document.body.appendChild(guide);
const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const textNodes=[];while(walker.nextNode())if(!['SCRIPT','STYLE'].includes(walker.currentNode.parentElement?.tagName))textNodes.push(walker.currentNode);textNodes.forEach(node=>{node.textContent=node.textContent.replace(/Blaine County Sheriff's Office/gi,"Sheriff's Office").replace(/Blaine County Kormánya/gi,'Kormánya').replace(/\s*&\s*Blaine County/gi,'').replace(/Blaine County/gi,'').replace(/ {2,}/g,' ')})
const show=()=>{guide.hidden=false;document.body.classList.add('guide-open');if(!location.pathname.endsWith('/segedlet'))history.pushState({guide:true},'','/segedlet')};
const hide=()=>{guide.hidden=true;document.body.classList.remove('guide-open');if(location.pathname.endsWith('/segedlet'))history.pushState({},'','/')};
help.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();show()},true);
const home=[...document.querySelectorAll('a')].find(a=>a.textContent.trim()==='BTK');if(home)home.addEventListener('click',e=>{if(!guide.hidden){e.preventDefault();hide()}},true);
addEventListener('popstate',()=>location.pathname.endsWith('/segedlet')?show():hide());if(location.pathname.endsWith('/segedlet'))show();
})();
